In [3]:
import numpy as np

array = np.arange(10)

print(array)
print(type(array))
print(array.dtype)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int32


In [4]:
float_arr = array / 2

print(float_arr)
print(type(float_arr))
print(float_arr.dtype)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
<class 'numpy.ndarray'>
float64


In [5]:
int_arr = float_arr.astype(np.int64)

print(int_arr)
print(type(int_arr))
print(int_arr.dtype)

[0 0 1 1 2 2 3 3 4 4]
<class 'numpy.ndarray'>
int64


In [7]:
prices = np.array([1, 3, -2, 9, 5, 7, 2])

prices

array([ 1,  3, -2,  9,  5,  7,  2])

In [8]:
signal_one = prices > 2
signal_two = prices > 4

print(signal_one)
print(signal_two)

[False  True False  True  True  True False]
[False False False  True  True  True False]


In [9]:
signal_one = signal_one.astype(np.int)
signal_two = signal_two.astype(np.int)

print(signal_one)
print(signal_two)

[0 1 0 1 1 1 0]
[0 0 0 1 1 1 0]


In [10]:
pos_one = 1 * signal_one
pos_two = 3 * signal_two

print(pos_one)
print(pos_two)

[0 1 0 1 1 1 0]
[0 0 0 3 3 3 0]


In [11]:
long_pos = pos_one + pos_two

print(long_pos)

[0 1 0 4 4 4 0]


In [12]:
my_prices = 10 * np.array([1, 3, -2, 9, 5, 7, 2])

print(my_prices)

[ 10  30 -20  90  50  70  20]


In [14]:
def generate_positions(prices):
    """
    Generate the following signals:
     - Long 30 share of stock when the price is above 50 dollars
     - Short 10 shares when it's below 20 dollars
    
    Parameters
    ----------
    prices : DataFrame
        Prices for each ticker and date
    
    Returns
    -------
    final_positions : DataFrame
        Final positions for each ticker and date
    """
    
    signal_long = (prices > 50).astype(np.int)
    signal_short = (prices < 20).astype(np.int)
  
# First try
#     signal_long = signal_long.astype(np.int)
#     signal_short = signal_short.astype(np.int)
    
    signal_long_act = 30 * signal_long
    signal_short_act = -1 * (10 * signal_short)
    
    return signal_long_act, signal_short_act
    
print(generate_positions(my_prices))

(array([ 0,  0,  0, 30,  0, 30,  0]), array([-10,   0, -10,   0,   0,   0,   0]))
